version: '2'  

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9001:9001"
    volumes:
      - ./config/nginx:/etc/nginx
    links:
      - cal

  cal:
    build: ./CALEngine/
    container_name: cal
    command: bash -c "cd /src; make clean bmi_fcgi && /usr/bin/spawn-fcgi -p 8002 -n -- ./bmi_fcgi --doc-features /data/athome1.bin --df /data/athome1.df --async-mode --threads 8"
    volumes:
      - ./CALEngine:/src
      - ./data:/data
    expose:
      - "8002"

  django:
    build:
      context: ./TrecCoreWeb
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./TrecCoreWeb:/app
    environment:
      - POSTGRES_USER=treccoreweb
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    build:
      context: ./TrecCoreWeb
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=treccoreweb
